version: 0.2

artifacts:
  files:
    - '**/*'
  base-directory: '.'

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing Terraform
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - bash named-profile.sh

  pre_build:
    commands:
      - terraform version
      - echo Verifying Terraform installation

  build:
    commands:
      - echo Starting deployment of infrastructure
      - pwd
      - ls -la
      - terraform init -backend-config="key=prod/terraform.tfstate"
      - terraform plan -var-file=prod.terraform.tfvars
      - terraform apply --auto-approve -var-file=prod.terraform.tfvars

  post_build:
    commands:
      - echo Terraform apply completed on `date`
