version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - sudo yum update -y
      - yum install git -y
      - dnf install -y httpd php php-mysqli mariadb105
      - echo testing initial setup of codebuild
      - echo installing terraform
      - yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform

  build:
    commands:
      - echo running terraform
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - echo installed terraform
  deploy:
    commands:
      - echo starting deployment of infrastructure
      - terraform plan -var-file=prod.terraform.tfvars
      

  